// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQL6BxBfrOLh1cLqW6_RgG9JOp9b4B_sE',
    appId: '1:1056677091119:web:af5a9bbcf1112a1eb1b3da',
    messagingSenderId: '1056677091119',
    projectId: 'reviewcoffe',
    authDomain: 'reviewcoffe.firebaseapp.com',
    databaseURL: 'https://reviewcoffe-default-rtdb.firebaseio.com',
    storageBucket: 'reviewcoffe.firebasestorage.app',
    measurementId: 'G-7C4XZF0GFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLOsgQGTxgG3zaJPWZx2bjCWKrPHFsjPQ',
    appId: '1:1056677091119:android:462fdc2d4512f433b1b3da',
    messagingSenderId: '1056677091119',
    projectId: 'reviewcoffe',
    databaseURL: 'https://reviewcoffe-default-rtdb.firebaseio.com',
    storageBucket: 'reviewcoffe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhZl-2bOttaZK7vnVGSLatFWr5pZofJhQ',
    appId: '1:1056677091119:ios:32d9bec7d041eaaeb1b3da',
    messagingSenderId: '1056677091119',
    projectId: 'reviewcoffe',
    databaseURL: 'https://reviewcoffe-default-rtdb.firebaseio.com',
    storageBucket: 'reviewcoffe.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhZl-2bOttaZK7vnVGSLatFWr5pZofJhQ',
    appId: '1:1056677091119:ios:32d9bec7d041eaaeb1b3da',
    messagingSenderId: '1056677091119',
    projectId: 'reviewcoffe',
    databaseURL: 'https://reviewcoffe-default-rtdb.firebaseio.com',
    storageBucket: 'reviewcoffe.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQL6BxBfrOLh1cLqW6_RgG9JOp9b4B_sE',
    appId: '1:1056677091119:web:b34bd4e40e0ec520b1b3da',
    messagingSenderId: '1056677091119',
    projectId: 'reviewcoffe',
    authDomain: 'reviewcoffe.firebaseapp.com',
    databaseURL: 'https://reviewcoffe-default-rtdb.firebaseio.com',
    storageBucket: 'reviewcoffe.firebasestorage.app',
    measurementId: 'G-633DRV8D74',
  );
}
